# https://code.roche.com/sergio.champel/hello-npm/-/blob/master/.gitlab-ci.yml
.shared_runners:
  tags:
    - amd64
    - docker
    - linux

default:
# https://docs.gitlab.com/ee/ci/caching/index.html
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#      - .npm/
#  before_script:
#    - npm ci --cache .npm --prefer-offline

code_quality:
  allow_failure: false

eslint-sast:
  allow_failure: false

nodejs-scan-sast:
  allow_failure: false

npm publish:
  #extends:
  #  - .shared_runners
  # https://hub.docker.com/_/node?tab=tags
  image: node:lts-alpine
  stage: deploy
  script:
    - echo '//code.roche.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

# include examples:
#   https://docs.gitlab.com/ee/ci/yaml/includes.html
include:
  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
  - template: Auto-DevOps.gitlab-ci.yml
