# https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
include:
  - template: Auto-DevOps.gitlab-ci.yml

# https://hub.docker.com/_/node?tab=tags
image: node:10.23-alpine

# https://code.roche.com/sergio.champel/hello-npm/-/blob/master/.gitlab-ci.yml
.shared_runners:
  tags:
    - Linux
    - docker
    - amd64

stages:
  - build
  - publish

npm install:
  extends:
    - .shared_runners
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

npm publish:
  extends:
    - .shared_runners
  needs: ["npm install"]
  stage: publish
  script:
    - echo '//code.roche.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish
  only:
    refs:
      - master

